### ISSUE TITLE
Fix dart2js tests on travis

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/typed_data#16]
https://travis-ci.org/dart-lang/typed_data/jobs/398049453

Seems there are a few constants that make dart2js sad...

**Comment by munificent** [comment]
I'm probably not the relevant one for this. @jmesserly or @sigmundch, want to take a look? I haven't been closely following the changes around large 64-bit-ish integers.

**Comment by sigmundch** [comment]
I'm not familiar with logic on these tests, but they need to be updated to run without using literals that can't be represented in JS, or split so that those large literals are only used in VM tests.

FWIW -  all of these large literals are used as parameters for int32x4, which are anyways truncated to 32-bit ints.

**Comment by chalin** [comment]
FYI, #17 splits tests across two Travis jobs, and the browsers tests have been disabled for now. That way we can get the build passing again.
